### ISSUE TITLE
fizzbuzz.py 생성

### ISSUE THREAD

**Issue by Kim-Yeon-Jun** [Team-usai3/team-fb-31415#1]
## Description
(간단히 할 일을 표현하세요.)
0 이상의 정수에 대해서 정수가 
3의 배수일 때 ‘fizz’, 
5의 배수일 때는 ‘buzz’, 
둘 모두의 배수일 때는 ‘fizzbuzz’ 출력

## Tasks

- [x] fizz
- [x] buzz
- [x] fizzbuzz
- [ ] 1 conditional statement 

## References

- [fizzbuzz 구현](https://shoark7.github.io/programming/algorithm/implement-fizzbuzz-like-developer)

**Comment by oohna-na** [comment]
굿굿!!
