### ISSUE TITLE
Fizzbuzz 구현

### ISSUE THREAD

**Issue by insu97** [Team-usai3/team-fb-31415#2]
## Description
1 ~ 20 까지 양의 정수에 대해, 그 수가 3의 배수라면 fizz, 5의 배수라면 buzz, 3과 5의 공배수면 fizzbuzz를 출력하는 기능을 구현하려고 합니다.

## Tasks

- [x] fizz
- [x] buzz
- [x] fizzbuzz

## References

- [fizzbuzz](https://en.wikipedia.org/wiki/Fizz_buzz)

**Comment by oohna-na** [comment]
굿굿!!
